import { createClient } from '@supabase/supabase-js';
import { settings } from '../config/settings.js';
import { log } from '../utils/logger.js';

const supabase = createClient(settings.supabaseUrl, settings.supabaseKey);

const REQUIRED_TABLES = [
    {
        name: 'reminders',
        sql: `CREATE TABLE IF NOT EXISTS reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  remote_jid TEXT NOT NULL,
  scheduled_time TIMESTAMPTZ NOT NULL,
  message TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);`
    },
    {
        name: 'usage_log',
        sql: `CREATE TABLE IF NOT EXISTS usage_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  type TEXT NOT NULL,
  amount NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`
    },
    {
        name: 'whitelist',
        sql: `CREATE TABLE IF NOT EXISTS whitelist (
  number TEXT PRIMARY KEY,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`
    },
    {
        name: 'memories',
        sql: `CREATE TABLE IF NOT EXISTS memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);`
    },
    {
        name: 'long_term_memories',
        sql: `CREATE TABLE IF NOT EXISTS long_term_memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  content TEXT NOT NULL,
  embedding vector(768),
  created_at TIMESTAMPTZ DEFAULT NOW()
);`
    }
];

export const checkDatabase = async () => {
    log.system('🔍 Checking Database Schema...');
    let missingTables = [];

    for (const table of REQUIRED_TABLES) {
        try {
            const { error } = await supabase
                .from(table.name)
                .select('id')
                .limit(1);

            if (error) {
                // PGRST116 is not found (single), but for select it might be different
                // Usually missing table returns 404 or specific message
                if (error.message.includes('does not exist')) {
                    log.warn(`[MISSING] Table '${table.name}' is missing.`);
                    missingTables.push(table);
                } else {
                    log.error(`Error checking table '${table.name}':`, error.message);
                }
            } else {
                log.success(`[OK] Table '${table.name}' is ready.`);
            }
        } catch (err) {
            log.error(`Failed to check table '${table.name}':`, err.message);
        }
    }

    if (missingTables.length > 0) {
        log.warn('\n--- SQL TO FIX MISSING TABLES ---');
        log.warn('Copy and run these in Supabase SQL Editor:');
        missingTables.forEach(t => {
            console.log(`\n-- Table: ${t.name}\n${t.sql}`);
        });
        log.warn('\n--- END OF SQL ---\n');
    } else {
        log.success('All tables are present and healthy.');
    }
};

// If run directly
if (import.meta.url.endsWith(process.argv[1])) {
    checkDatabase();
}
